
const PORTAL_KEY='rihla_3ac_portal_v1';
const LESSON_KEY='capitalisme_3ac_mobile_v1';
const defaultState={name:'',teacher:'الأستاذ أحمد بوعمود',announcement:'مرحبا بكم في بوابة رحلة الثالثة إعدادي. ابدأوا بمحطة التاريخ الأولى، واجمعوا الأوسمة خطوة بخطوة.',opened:{capitalisme:true},notes:'',visited:{}};
const subjects={history:{title:'التاريخ',icon:'📜',total:8,active:1},geography:{title:'الجغرافيا',icon:'🌍',total:6,active:0},citizenship:{title:'التربية على المواطنة',icon:'🤝',total:4,active:0}};
function getPortal(){try{return {...defaultState,...(JSON.parse(localStorage.getItem(PORTAL_KEY))||{})}}catch(e){return {...defaultState}}}
function savePortal(s){localStorage.setItem(PORTAL_KEY,JSON.stringify(s))}
function patchPortal(fn){const s=getPortal();fn(s);savePortal(s);renderCommon();return s}
function getLessonState(){try{return JSON.parse(localStorage.getItem(LESSON_KEY))||{}}catch(e){return {}}}
function toast(msg){const t=document.getElementById('toast'); if(!t){alert(msg);return} t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
function setName(){const el=document.getElementById('studentName'); const name=(el?.value||'').trim(); if(!name){toast('اكتب اسم التلميذ أولاً.');return} patchPortal(s=>s.name=name); toast('تم حفظ الاسم داخل البوابة.');}
function resetPortal(){if(confirm('تصفير تقدم البوابة؟ لن يحذف تقدم تطبيق درس الرأسمالية إلا إذا اخترت ذلك من داخله.')){localStorage.removeItem(PORTAL_KEY);toast('تم تصفير البوابة.');setTimeout(()=>location.reload(),700)}}
function markVisited(id){patchPortal(s=>{s.visited[id]=true})}
function renderCommon(){const s=getPortal(), l=getLessonState(); const name=s.name||l.name||'تلميذ مستكشف';document.querySelectorAll('[data-student]').forEach(e=>e.textContent=name);document.querySelectorAll('[data-teacher]').forEach(e=>e.textContent=s.teacher||'الأستاذ أحمد بوعمود');document.querySelectorAll('[data-announcement]').forEach(e=>e.textContent=s.announcement||defaultState.announcement);const score=l.score||0;document.querySelectorAll('[data-score]').forEach(e=>e.textContent=score);const done=Object.keys(l.completed||{}).length;document.querySelectorAll('[data-capitalisme-progress]').forEach(e=>e.textContent=done+'/7');document.querySelectorAll('[data-capitalisme-bar]').forEach(e=>e.style.width=Math.min(100,Math.round(done/7*100))+'%');const active=1;document.querySelectorAll('[data-open-lessons]').forEach(e=>e.textContent=active);document.querySelectorAll('[data-total-lessons]').forEach(e=>e.textContent=subjects.history.total+subjects.geography.total+subjects.citizenship.total);}
function saveTeacherSettings(){const teacher=document.getElementById('teacherName')?.value.trim();const announcement=document.getElementById('announcement')?.value.trim();const notes=document.getElementById('teacherNotes')?.value.trim();patchPortal(s=>{if(teacher)s.teacher=teacher;if(announcement)s.announcement=announcement;s.notes=notes||''});toast('تم حفظ إعدادات البوابة محلياً على هذا الهاتف.');}
function fillTeacher(){const s=getPortal(); if(document.getElementById('teacherName'))document.getElementById('teacherName').value=s.teacher||''; if(document.getElementById('announcement'))document.getElementById('announcement').value=s.announcement||''; if(document.getElementById('teacherNotes'))document.getElementById('teacherNotes').value=s.notes||'';}
function filterLessons(q, tag){q=(q||'').toLowerCase().trim();document.querySelectorAll('[data-lesson]').forEach(card=>{const hay=(card.textContent||'').toLowerCase();const okQ=!q||hay.includes(q);const okT=!tag||card.dataset.subject===tag||card.dataset.status===tag;card.style.display=(okQ&&okT)?'grid':'none'});const any=[...document.querySelectorAll('[data-lesson]')].some(c=>c.style.display!=='none');const empty=document.querySelector('.empty'); if(empty)empty.style.display=any?'none':'block';}
function setupFilters(){const search=document.getElementById('lessonSearch'); if(search)search.addEventListener('input',()=>filterLessons(search.value,document.querySelector('.chip.active')?.dataset.filter||''));document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');filterLessons(search?.value||'',c.dataset.filter||'')}))}
function soon(title){toast('محطة "'+title+'" مهيأة داخل البوابة وسنضيف تطبيقها التفاعلي لاحقاً.');}
function exportPlan(){const content=`مشروع بوابة رحلة الثالثة إعدادي\n\nالأستاذ: ${getPortal().teacher}\n\nالفكرة: بوابة مركزية للهاتف تجمع دروس التاريخ والجغرافيا والتربية على المواطنة كتطبيقات تعليمية قصيرة.\n\nالمحطة الجاهزة: ازدهار الرأسمالية الأوربية خلال القرن 19.\n\nالمحطات المقبلة: الإمبريالية، الضغط الاستعماري، فرض الحماية، الولايات المتحدة، اليابان، روسيا، مصر، نيجيريا، النهج الجغرافي، نحن والعالم، التراث.\n\nملاحظات الأستاذ:\n${getPortal().notes||'لا توجد ملاحظات بعد.'}`;const blob=new Blob([content],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rihla-3ac-plan.txt';a.click();URL.revokeObjectURL(a.href)}
document.addEventListener('DOMContentLoaded',()=>{renderCommon();fillTeacher();setupFilters();});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
